title: Me N Lifey In Sunset - When life shines bright on you! (Multiverse view)
author: JoÃ£o Neto
email: joao@neto.pt
description: >-
  A gallery displaying moments when life is shining bright.

social:
  twitter: ptruoong
  facebook: https://www.facebook.com/patrick.truong.184
  instagram: ptruoong
  github: patruong
  linkedin: https://www.linkedin.com/in/patrick-truong-768462b1/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
